import * as fs from 'fs';
import * as path from 'path';
export class ReportGenerator {
    constructor() {
        this.reportsDir = path.join(process.cwd(), 'reports');
        if (!fs.existsSync(this.reportsDir)) {
            fs.mkdirSync(this.reportsDir, { recursive: true });
        }
    }
    generateMarkdownReport(strategyName, metrics, monteCarlo, extraMetrics) {
        const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
        const filename = `Report_${strategyName}_${timestamp}.md`;
        const filePath = path.join(this.reportsDir, filename);
        const content = `
# Institutional Strategy Report: ${strategyName}
**Date:** ${new Date().toISOString()}

## 1. Performance Summary
| Metric | Value |
|--------|-------|
| Total Return | ${(metrics.totalReturn * 100).toFixed(2)}% |
| Win Rate | ${(metrics.winRate * 100).toFixed(2)}% |
| Profit Factor | ${metrics.profitFactor.toFixed(2)} |
| Sharpe Ratio | ${metrics.sharpeRatio.toFixed(2)} |
| **Calmar Ratio** | **${extraMetrics.calmar.toFixed(2)}** |
| **Omega Ratio** | **${extraMetrics.omega.toFixed(2)}** |
| Max Drawdown | ${(metrics.maxDrawdown * 100).toFixed(2)}% |

## 2. Risk Analysis (Monte Carlo - ${monteCarlo.simulations.length} runs)
- **VaR 95%:** ${(monteCarlo.p95_drawdown * 100).toFixed(2)}%
- **Ruin Probability:** ${(monteCarlo.ruinProbability * 100).toFixed(2)}%
- **P95 Expected Return:** ${(monteCarlo.p95_return * 100).toFixed(2)}%

## 3. Trade Statistics
- Total Trades: ${metrics.totalTrades}
- Avg Win: ${metrics.averageWin.toFixed(2)}
- Avg Loss: ${metrics.averageLoss.toFixed(2)}
- Expectancy: ${metrics.expectancy.toFixed(2)}

---
*Generated by RoboCrypto Institutional Engine*
    `;
        fs.writeFileSync(filePath, content.trim());
        return filePath;
    }
    generateLatexReport(strategyName, metrics, monteCarlo, extraMetrics) {
        const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
        const filename = `Report_${strategyName}_${timestamp}.tex`;
        const filePath = path.join(this.reportsDir, filename);
        const content = `
\\documentclass{article}
\\usepackage{graphicx}
\\usepackage{booktabs}
\\title{Institutional Strategy Report: ${strategyName}}
\\author{RoboCrypto Engine}
\\date{\\today}

\\begin{document}

\\maketitle

\\section{Executive Summary}
This report outlines the backtesting performance of the ${strategyName} strategy.

\\section{Performance Metrics}
\\begin{table}[h]
\\centering
\\begin{tabular}{lr}
\\toprule
Metric & Value \\\\
\\midrule
Total Return & ${(metrics.totalReturn * 100).toFixed(2)}\\% \\\\
Win Rate & ${(metrics.winRate * 100).toFixed(2)}\\% \\\\
Profit Factor & ${metrics.profitFactor.toFixed(2)} \\\\
Sharpe Ratio & ${metrics.sharpeRatio.toFixed(2)} \\\\
\\textbf{Calmar Ratio} & \\textbf{${extraMetrics.calmar.toFixed(2)}} \\\\
\\textbf{Omega Ratio} & \\textbf{${extraMetrics.omega.toFixed(2)}} \\\\
Max Drawdown & ${(metrics.maxDrawdown * 100).toFixed(2)}\\% \\\\
\\bottomrule
\\end{tabular}
\\end{table}

\\section{Risk Analysis (Monte Carlo)}
\\begin{itemize}
    \\item 95\\% VaR: ${(monteCarlo.p95_drawdown * 100).toFixed(2)}\\%
    \\item Ruin Probability: ${(monteCarlo.ruinProbability * 100).toFixed(2)}\\%
    \\item P95 Return: ${(monteCarlo.p95_return * 100).toFixed(2)}\\%
\\end{itemize}

\\end{document}
    `;
        fs.writeFileSync(filePath, content.trim());
        return filePath;
    }
}
